
name: docker build
on:
  push:
    branches:
      - master

jobs:
  traefik:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@master
      - name: build
        uses: triptixx/action-docker-build@master
        with:
          repo: traefik-dev
      - name: test
        uses: triptixx/action-docker-test@master
        with:
          verbose: true
          repo: traefik-dev
          run_args: -v /var/run/docker.sock:/var/run/docker.sock:ro -e ACME_MAIL=${{ secrets.le_mail }} -e DOCKER_ENDPOINT=unix:///var/run/docker.sock -e ACME_TEST=true
          exec_pre: /traefik/traefik healthcheck
      - name: publish
        uses: triptixx/action-docker-publish@master
        with:
          docker_username: ${{ secrets.docker_username }}
          docker_password: ${{ secrets.docker_password }}
          from: traefik-dev
          repo: ${{ secrets.docker_username }}/traefik
          tags: latest,%label org.label-schema.version | %auto
      - name: docker-scout
        uses: docker/scout-action@v1
        with:
          dockerhub-user: ${{ secrets.docker_username }}
          dockerhub-password: ${{ secrets.docker_password }}
          command: cves
          image: ${{ secrets.docker_username }}/traefik:latest
